/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-12-02 17:24:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.dao.WishlistDao;
import com.bean.User;

public final class cheackout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1764694953184L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.bean.User");
    _jspx_imports_classes.add("com.dao.WishlistDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");

    User u = null;
    if(session!=null)
    {
    	if(session.getAttribute("u")!=null)
    	{
    		u=(User)session.getAttribute("u");
    	}
    }

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Electro - Electronics Website Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid px-5 d-none border-bottom d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-start mb-lg-0\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted me-2\"> Help</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted mx-2\"> Support</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted ms-2\"> Contact</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                <small class=\"text-dark\">Call Us:</small>\r\n");
      out.write("                <a href=\"#\" class=\"text-muted\">(+012) 1234 567890</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted me-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                USD</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Euro</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Dolar</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted mx-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                English</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> English</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Turkish</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Spanol</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Italiano</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted ms-2\" data-bs-toggle=\"dropdown\"><small><i\r\n");
      out.write("                                    class=\"fa fa-home me-2\"></i> My Dashboard</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Login</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Wishlist</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Card</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Notifications</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Account Settings</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Account</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Log Out</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid px-5 py-4 d-none d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center text-center\">\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-start\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a href=\"\" class=\"navbar-brand p-0\">\r\n");
      out.write("                        <h1 class=\"display-5 text-primary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-secondary me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-6 text-center\">\r\n");
      out.write("                <div class=\"position-relative ps-4\">\r\n");
      out.write("                    <div class=\"d-flex border rounded-pill\">\r\n");
      out.write("                        <input class=\"form-control border-0 rounded-pill w-100 py-3\" type=\"text\"\r\n");
      out.write("                            data-bs-target=\"#dropdownToggle123\" placeholder=\"Search Looking For?\">\r\n");
      out.write("                        <select class=\"form-select text-dark border-0 border-start rounded-0 p-3\" style=\"width: 200px;\">\r\n");
      out.write("                            <option value=\"All Category\">All Category</option>\r\n");
      out.write("                            <option value=\"Pest Control-2\">Category 1</option>\r\n");
      out.write("                            <option value=\"Pest Control-3\">Category 2</option>\r\n");
      out.write("                            <option value=\"Pest Control-4\">Category 3</option>\r\n");
      out.write("                            <option value=\"Pest Control-5\">Category 4</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary rounded-pill py-3 px-5\" style=\"border: 0;\"><i\r\n");
      out.write("                                class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    ");

                       if(u!=null)
                       {
                    
      out.write("\r\n");
      out.write("                    <a href=\"wishlist.jsp\" class=\"text-muted d-flex align-items-center justify-content-center me-3 \"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\" far fa-heart\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("                        <span class=\"text-dark ms-2\">$0.00</span></a>\r\n");
      out.write("                     \r\n");
      out.write("                     ");
 
                       }                     
                     
      out.write("   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar & Hero Start -->\r\n");
      out.write("    <div class=\"container-fluid nav-bar p-0\">\r\n");
      out.write("        <div class=\"row gx-0 bg-primary px-5 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <nav class=\"navbar navbar-light position-relative\" style=\"width: 250px;\">\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light bg-primary \">\r\n");
      out.write("                    <a href=\"\" class=\"navbar-brand d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"display-5 text-secondary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-white me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                        data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"fa fa-bars fa-1x\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                            <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                            <a href=\"shop.jsp\" class=\"nav-item nav-link\">Shop</a>\r\n");
      out.write("                            ");

									if(u!=null)
									{  
                               
      out.write("\r\n");
      out.write("                            <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Account</a>    \r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <a href=\"wishlist.jsp\" class=\"dropdown-item\">Wishlist(");
      out.print( session.getAttribute("wishlist_count") );
      out.write(")</a>\r\n");
      out.write("                                    <a href=\"cart.jsp\" class=\"dropdown-item\">Shopping Cart(");
      out.print( session.getAttribute("cart_count") );
      out.write(")</a>\r\n");
      out.write("                                    <a href=\"myoder.jsp\" class=\"dropdown-item\">MyOder</a>\r\n");
      out.write("                                    <a href=\"cheackout.jsp\" class=\"dropdown-item\">Cheackout</a>\r\n");
      out.write("                                    <a href=\"404.jsp\" class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        ");

									}                            
                            
      out.write("\r\n");
      out.write("                            <a href=\"contact.jsp\" class=\"nav-item nav-link me-2\">Contact</a>    \r\n");
      out.write("                            \r\n");
      out.write("                            ");

                                if(u==null)
                                {
                               
      out.write("\r\n");
      out.write("                               <a href=\"signup.jsp\" class=\"nav-item nav-link me-2\">Sign Up</a>\r\n");
      out.write("                               <a href=\"login.jsp\" class=\"nav-item nav-link me-2\">Login</a>\r\n");
      out.write("                               ");

                                }
                                else
                                {
                                
      out.write("	\r\n");
      out.write("                                	<a href=\"logout.jsp\" class=\"nav-item nav-link me-3\">Logout(");
      out.print( u.getFname()  );
      out.write(")</a>\r\n");
      out.write("                                 	 \r\n");
      out.write("                                 	 <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"logout.jsp\" class=\"nav-item nav-link me-5 \" data-bs-toggle=\"dropdown\"><img src=\"profile_picture/");
      out.print(u.getProfile_picture() );
      out.write("\" alt=\"Profile Picture\"  style=\"width:60px; height:60px; border-radius: 50%; \"></a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <a href=\"profile.jsp\" class=\"dropdown-item\">Profile</a>\r\n");
      out.write("                                    <a href=\"change-password.jsp\" class=\"dropdown-item\">Change Password</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                	\r\n");
      out.write("                                	\r\n");
      out.write("                                	\r\n");
      out.write("                              ");
  
                                }
                            
      out.write("\r\n");
      out.write("                            <div class=\"nav-item dropdown d-block d-lg-none mb-3\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">All Category</a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <ul class=\"list-unstyled categories-bars\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Accessories</a>\r\n");
      out.write("                                                <span>(3)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Electronics & Computer</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Laptops & Desktops</a>\r\n");
      out.write("                                                <span>(2)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Mobiles & Tablets</a>\r\n");
      out.write("                                                <span>(8)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">SmartPhone & Smart TV</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar & Hero End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Single Page Header start -->\r\n");
      out.write("    <div class=\"container-fluid page-header py-5\">\r\n");
      out.write("        <h1 class=\"text-center text-white display-6 wow fadeInUp\" data-wow-delay=\"0.1s\">Cheackout Page</h1>\r\n");
      out.write("        <ol class=\"breadcrumb justify-content-center mb-0 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("            <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item active text-white\">Cheackout</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Single Page Header End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Searvices Start -->\r\n");
      out.write("    <div class=\"container-fluid px-0\">\r\n");
      out.write("        <div class=\"row g-0\">\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-start border-end wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fa fa-sync-alt fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Free Return</h6>\r\n");
      out.write("                            <p class=\"mb-0\">30 days money back guarantee!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-end wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fab fa-telegram-plane fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Free Shipping</h6>\r\n");
      out.write("                            <p class=\"mb-0\">Free shipping on all order</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-end wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fas fa-life-ring fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Support 24/7</h6>\r\n");
      out.write("                            <p class=\"mb-0\">We support online 24 hrs a day</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-end wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fas fa-credit-card fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Receive Gift Card</h6>\r\n");
      out.write("                            <p class=\"mb-0\">Recieve gift all over oder $50</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-end wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fas fa-lock fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Secure Payment</h6>\r\n");
      out.write("                            <p class=\"mb-0\">We Value Your Security</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 col-md-4 col-lg-2 border-end wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"fas fa-blog fa-2x text-primary\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h6 class=\"text-uppercase mb-2\">Online Service</h6>\r\n");
      out.write("                            <p class=\"mb-0\">Free return products in 30 days</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Searvices End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Checkout Page Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-light overflow-hidden py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <h1 class=\"mb-4 wow fadeInUp\" data-wow-delay=\"0.1s\">Billing details</h1>\r\n");
      out.write("            <form action=\"#\">\r\n");
      out.write("                <div class=\"row g-5\">\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-6 col-xl-6 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                                <div class=\"form-item w-100\">\r\n");
      out.write("                                    <label class=\"form-label my-3\">First Name<sup>*</sup></label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                                <div class=\"form-item w-100\">\r\n");
      out.write("                                    <label class=\"form-label my-3\">Last Name<sup>*</sup></label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Company Name<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Address <sup>*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"House Number Street Name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Town/City<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Country<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Postcode/Zip<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Mobile<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"tel\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <label class=\"form-label my-3\">Email Address<sup>*</sup></label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check my-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"form-check-input\" id=\"Account-1\" name=\"Accounts\"\r\n");
      out.write("                                value=\"Accounts\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"Account-1\">Create an account?</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <div class=\"form-check my-3\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"Address-1\" name=\"Address\"\r\n");
      out.write("                                value=\"Address\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"Address-1\">Ship to a different address?</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-item\">\r\n");
      out.write("                            <textarea name=\"text\" class=\"form-control\" spellcheck=\"false\" cols=\"30\" rows=\"11\"\r\n");
      out.write("                                placeholder=\"Oreder Notes (Optional)\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-6 col-xl-6 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"col\" class=\"text-start\">Name</th>\r\n");
      out.write("                                        <th scope=\"col\">Model</th>\r\n");
      out.write("                                        <th scope=\"col\">Price</th>\r\n");
      out.write("                                        <th scope=\"col\">Quantity</th>\r\n");
      out.write("                                        <th scope=\"col\">Total</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"row\" class=\"text-start py-4\">\r\n");
      out.write("                                            Apple iPad Mini\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">G2356</td>\r\n");
      out.write("                                        <td class=\"py-4\">$269.00</td>\r\n");
      out.write("                                        <td class=\"py-4 text-center\">2</td>\r\n");
      out.write("                                        <td class=\"py-4\">$538.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"row\" class=\"text-start py-4\">\r\n");
      out.write("                                            Apple iPad Mini\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">G2356</td>\r\n");
      out.write("                                        <td class=\"py-4\">$269.00</td>\r\n");
      out.write("                                        <td class=\"py-4\">2</td>\r\n");
      out.write("                                        <td class=\"py-4\">$538.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"row\" class=\"text-start py-4\">\r\n");
      out.write("                                            Apple iPad Mini\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">G2356</td>\r\n");
      out.write("                                        <td class=\"py-4\">$269.00</td>\r\n");
      out.write("                                        <td class=\"py-4\">2</td>\r\n");
      out.write("                                        <td class=\"py-4\">$538.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"row\" class=\"text-start py-4\">\r\n");
      out.write("                                            Apple iPad Mini\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">G2356</td>\r\n");
      out.write("                                        <td class=\"py-4\">$269.00</td>\r\n");
      out.write("                                        <td class=\"py-4\">2</td>\r\n");
      out.write("                                        <td class=\"py-4\">$538.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"text-center\">\r\n");
      out.write("                                        <th scope=\"row\" class=\"text-start py-4\">\r\n");
      out.write("                                            Apple iPad Mini\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">G2356</td>\r\n");
      out.write("                                        <td class=\"py-4\">$269.00</td>\r\n");
      out.write("                                        <td class=\"py-4\">2</td>\r\n");
      out.write("                                        <td class=\"py-4\">$538.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\"></td>\r\n");
      out.write("                                        <td class=\"py-4\"></td>\r\n");
      out.write("                                        <td class=\"py-4\">\r\n");
      out.write("                                            <p class=\"mb-0 text-dark py-2\">Subtotal</p>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td class=\"py-4\">\r\n");
      out.write("                                            <div class=\"py-2 text-center border-bottom border-top\">\r\n");
      out.write("                                                <p class=\"mb-0 text-dark\">$1134.00</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">\r\n");
      out.write("                                            <p class=\"mb-0 text-dark py-4\">Shipping</p>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td colspan=\"3\" class=\"py-4\">\r\n");
      out.write("                                            <div class=\"form-check text-start\">\r\n");
      out.write("                                                <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\"\r\n");
      out.write("                                                    id=\"Shipping-1\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"Shipping-1\">Free Shipping</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-check text-start\">\r\n");
      out.write("                                                <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\"\r\n");
      out.write("                                                    id=\"Shipping-2\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"Shipping-2\">Flat rate:\r\n");
      out.write("                                                    $15.00</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-check text-start\">\r\n");
      out.write("                                                <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\"\r\n");
      out.write("                                                    id=\"Shipping-3\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"Shipping-3\">Local Pickup:\r\n");
      out.write("                                                    $8.00</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <td class=\"py-4\">\r\n");
      out.write("                                            <p class=\"mb-0 text-dark text-uppercase py-2\">TOTAL</p>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td class=\"py-4\"></td>\r\n");
      out.write("                                        <td class=\"py-4\"></td>\r\n");
      out.write("                                        <td class=\"py-4\">\r\n");
      out.write("                                            <div class=\"py-2 text-center border-bottom border-top\">\r\n");
      out.write("                                                <p class=\"mb-0 text-dark\">$135.00</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-0 text-center align-items-center justify-content-center border-bottom py-2\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"form-check text-start my-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Transfer-1\"\r\n");
      out.write("                                        name=\"Transfer\" value=\"Transfer\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"Transfer-1\">Direct Bank Transfer</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"text-start text-dark\">Make your payment directly into our bank account. Please\r\n");
      out.write("                                    use your Order ID as the payment reference. Your order will not be shipped until the\r\n");
      out.write("                                    funds have cleared in our account.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-2\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"form-check text-start my-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Payments-1\"\r\n");
      out.write("                                        name=\"Payments\" value=\"Payments\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"Payments-1\">Check Payments</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-2\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"form-check text-start my-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Delivery-1\"\r\n");
      out.write("                                        name=\"Delivery\" value=\"Delivery\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"Delivery-1\">Cash On Delivery</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-2\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"form-check text-start my-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Paypal-1\"\r\n");
      out.write("                                        name=\"Paypal\" value=\"Paypal\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"Paypal-1\">Paypal</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4 text-center align-items-center justify-content-center pt-4\">\r\n");
      out.write("                            <button type=\"button\"\r\n");
      out.write("                                class=\"btn btn-primary border-secondary py-3 px-4 text-uppercase w-100 text-primary\">Place\r\n");
      out.write("                                Order</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Checkout Page End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid footer py-5 wow fadeIn\" data-wow-delay=\"0.2s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-4 rounded mb-5\" style=\"background: rgba(255, 255, 255, .03);\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Address</h4>\r\n");
      out.write("                            <p class=\"mb-2\">123 Street New York.USA</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fas fa-envelope fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Mail Us</h4>\r\n");
      out.write("                            <p class=\"mb-2\">info@example.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fa fa-phone-alt fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Telephone</h4>\r\n");
      out.write("                            <p class=\"mb-2\">(+012) 3456 7890</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fab fa-firefox-browser fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Yoursite@ex.com</h4>\r\n");
      out.write("                            <p class=\"mb-2\">(+012) 3456 7890</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <div class=\"footer-item\">\r\n");
      out.write("                            <h4 class=\"text-primary mb-4\">Newsletter</h4>\r\n");
      out.write("                            <p class=\"text-white mb-3\">Dolor amet sit justo amet elitr clita ipsum elitr est.Lorem ipsum\r\n");
      out.write("                                dolor sit amet, consectetur adipiscing elit consectetur adipiscing elit.</p>\r\n");
      out.write("                            <div class=\"position-relative mx-auto rounded-pill\">\r\n");
      out.write("                                <input class=\"form-control rounded-pill w-100 py-3 ps-4 pe-5\" type=\"text\"\r\n");
      out.write("                                    placeholder=\"Enter your email\">\r\n");
      out.write("                                <button type=\"button\"\r\n");
      out.write("                                    class=\"btn btn-primary rounded-pill position-absolute top-0 end-0 py-2 mt-2 me-2\">SignUp</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Customer Service</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Contact Us</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Returns</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Order History</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Site Map</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Testimonials</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> My Account</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Unsubscribe Notification</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Information</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> About Us</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Delivery infomation</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Privacy Policy</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Terms & Conditions</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Warranty</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> FAQ</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Seller Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Extras</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Brands</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Gift Vouchers</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Affiliates</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Wishlist</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Order History</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Track Your Order</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Track Your Order</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row g-4 align-items-center\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-md-0\">\r\n");
      out.write("                    <span class=\"text-white\"><a href=\"#\" class=\"border-bottom text-white\"><i\r\n");
      out.write("                                class=\"fas fa-copyright text-light me-2\"></i>Your Site Name</a>, All right\r\n");
      out.write("                        reserved.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end text-white\">\r\n");
      out.write("\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->\r\n");
      out.write("                    <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->\r\n");
      out.write("                    <!--/*** you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". ***/-->\r\n");
      out.write("                    Designed By <a class=\"border-bottom text-white\" href=\"https://htmlcodex.com\">HTML Codex</a>.\r\n");
      out.write("                    Distributed By <a class=\"border-bottom text-white\" href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-primary btn-lg-square back-to-top\"><i class=\"fa fa-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
