/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-11-05 17:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Electro - Electronics Website Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid px-5 d-none border-bottom d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-start mb-lg-0\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted me-2\"> Help</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted mx-2\"> Support</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted ms-2\"> Contact</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                <small class=\"text-dark\">Call Us:</small>\r\n");
      out.write("                <a href=\"#\" class=\"text-muted\">(+012) 1234 567890</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted me-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                USD</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Euro</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Dolar</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted mx-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                English</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> English</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Turkish</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Spanol</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Italiano</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted ms-2\" data-bs-toggle=\"dropdown\"><small><i\r\n");
      out.write("                                    class=\"fa fa-home me-2\"></i> My Dashboard</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Login</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Wishlist</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Card</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Notifications</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Account Settings</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Account</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Log Out</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid px-5 py-4 d-none d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center text-center\">\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-start\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a href=\"\" class=\"navbar-brand p-0\">\r\n");
      out.write("                        <h1 class=\"display-5 text-primary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-secondary me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-6 text-center\">\r\n");
      out.write("                <div class=\"position-relative ps-4\">\r\n");
      out.write("                    <div class=\"d-flex border rounded-pill\">\r\n");
      out.write("                        <input class=\"form-control border-0 rounded-pill w-100 py-3\" type=\"text\"\r\n");
      out.write("                            data-bs-target=\"#dropdownToggle123\" placeholder=\"Search Looking For?\">\r\n");
      out.write("                        <select class=\"form-select text-dark border-0 border-start rounded-0 p-3\" style=\"width: 200px;\">\r\n");
      out.write("                            <option value=\"All Category\">All Category</option>\r\n");
      out.write("                            <option value=\"Pest Control-2\">Category 1</option>\r\n");
      out.write("                            <option value=\"Pest Control-3\">Category 2</option>\r\n");
      out.write("                            <option value=\"Pest Control-4\">Category 3</option>\r\n");
      out.write("                            <option value=\"Pest Control-5\">Category 4</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary rounded-pill py-3 px-5\" style=\"border: 0;\"><i\r\n");
      out.write("                                class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center me-3\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-random\"></i></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center me-3\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("                        <span class=\"text-dark ms-2\">$0.00</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar & Hero Start -->\r\n");
      out.write("    <div class=\"container-fluid nav-bar p-0\">\r\n");
      out.write("        <div class=\"row gx-0 bg-primary px-5 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <nav class=\"navbar navbar-light position-relative\" style=\"width: 250px;\">\r\n");
      out.write("                    <button class=\"navbar-toggler border-0 fs-4 w-100 px-0 text-start\" type=\"button\"\r\n");
      out.write("                        data-bs-toggle=\"collapse\" data-bs-target=\"#allCat\">\r\n");
      out.write("                        <h4 class=\"m-0\"><i class=\"fa fa-bars me-2\"></i>All Categories</h4>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse rounded-bottom\" id=\"allCat\">\r\n");
      out.write("                        <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                            <ul class=\"list-unstyled categories-bars\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Accessories</a>\r\n");
      out.write("                                        <span>(3)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Electronics & Computer</a>\r\n");
      out.write("                                        <span>(5)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Laptops & Desktops</a>\r\n");
      out.write("                                        <span>(2)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Mobiles & Tablets</a>\r\n");
      out.write("                                        <span>(8)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">SmartPhone & Smart TV</a>\r\n");
      out.write("                                        <span>(5)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light bg-primary \">\r\n");
      out.write("                    <a href=\"\" class=\"navbar-brand d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"display-5 text-secondary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-white me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                        data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"fa fa-bars fa-1x\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                            <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                            <a href=\"shop.jsp\" class=\"nav-item nav-link\">Shop</a>\r\n");
      out.write("                            <a href=\"single.jsp\" class=\"nav-item nav-link\">Single Page</a>\r\n");
      out.write("                            <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <a href=\"bestseller.jsp\" class=\"dropdown-item\">Bestseller</a>\r\n");
      out.write("                                    <a href=\"cart.jsp\" class=\"dropdown-item\">Cart Page</a>\r\n");
      out.write("                                    <a href=\"cheackout.jsp\" class=\"dropdown-item\">Cheackout</a>\r\n");
      out.write("                                    <a href=\"404.jsp\" class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"contact.jsp\" class=\"nav-item nav-link me-2\">Contact</a>\r\n");
      out.write("                            <a href=\"signup.jsp\" class=\"nav-item nav-link me-2\">Sign Up</a>\r\n");
      out.write("                            <a href=\"contact.jsp\" class=\"nav-item nav-link me-2\">Login</a>\r\n");
      out.write("                            <div class=\"nav-item dropdown d-block d-lg-none mb-3\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">All Category</a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <ul class=\"list-unstyled categories-bars\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Accessories</a>\r\n");
      out.write("                                                <span>(3)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Electronics & Computer</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Laptops & Desktops</a>\r\n");
      out.write("                                                <span>(2)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Mobiles & Tablets</a>\r\n");
      out.write("                                                <span>(8)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">SmartPhone & Smart TV</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar & Hero End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
