/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-11-13 04:53:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.Product;
import com.bean.User;

public final class seller_002dprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/seller-header.jsp", Long.valueOf(1762961162393L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.bean.User");
    _jspx_imports_classes.add("com.bean.Product");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");

    User u = null;
    if(session!=null)
    {
    	if(session.getAttribute("u")!=null)
    	{
    		u=(User)session.getAttribute("u");
    	}
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Electro - Electronics Website Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid px-5 d-none border-bottom d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-start mb-lg-0\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted me-2\"> Help</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted mx-2\"> Support</a><small> / </small>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted ms-2\"> Contact</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                <small class=\"text-dark\">Call Us:</small>\r\n");
      out.write("                <a href=\"#\" class=\"text-muted\">(+012) 1234 567890</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\" style=\"height: 45px;\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted me-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                USD</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Euro</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Dolar</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted mx-2\" data-bs-toggle=\"dropdown\"><small>\r\n");
      out.write("                                English</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> English</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Turkish</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Spanol</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Italiano</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle text-muted ms-2\" data-bs-toggle=\"dropdown\"><small><i\r\n");
      out.write("                                    class=\"fa fa-home me-2\"></i> My Dashboard</small></a>\r\n");
      out.write("                        <div class=\"dropdown-menu rounded\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Login</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Wishlist</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Card</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Notifications</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Account Settings</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> My Account</a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\"> Log Out</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid px-5 py-4 d-none d-lg-block\">\r\n");
      out.write("        <div class=\"row gx-0 align-items-center text-center\">\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-start\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a href=\"seller-index.jsp\" class=\"navbar-brand p-0\">\r\n");
      out.write("                        <h1 class=\"display-5 text-primary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-secondary me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-6 text-center\">\r\n");
      out.write("                <div class=\"position-relative ps-4\">\r\n");
      out.write("                    <div class=\"d-flex border rounded-pill\">\r\n");
      out.write("                        <input class=\"form-control border-0 rounded-pill w-100 py-3\" type=\"text\"\r\n");
      out.write("                            data-bs-target=\"#dropdownToggle123\" placeholder=\"Search Looking For?\">\r\n");
      out.write("                        <select class=\"form-select text-dark border-0 border-start rounded-0 p-3\" style=\"width: 200px;\">\r\n");
      out.write("                            <option value=\"All Category\">All Category</option>\r\n");
      out.write("                            <option value=\"Pest Control-2\">Category 1</option>\r\n");
      out.write("                            <option value=\"Pest Control-3\">Category 2</option>\r\n");
      out.write("                            <option value=\"Pest Control-4\">Category 3</option>\r\n");
      out.write("                            <option value=\"Pest Control-5\">Category 4</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary rounded-pill py-3 px-5\" style=\"border: 0;\"><i\r\n");
      out.write("                                class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-lg-3 text-center text-lg-end\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center me-3\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-random\"></i></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center me-3\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-muted d-flex align-items-center justify-content-center\"><span\r\n");
      out.write("                            class=\"rounded-circle btn-md-square border\"><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("                        <span class=\"text-dark ms-2\">$0.00</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar & Hero Start -->\r\n");
      out.write("    <div class=\"container-fluid nav-bar p-0\">\r\n");
      out.write("        <div class=\"row gx-0 bg-primary px-5 align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <nav class=\"navbar navbar-light position-relative\" style=\"width: 250px;\">\r\n");
      out.write("                    <button class=\"navbar-toggler border-0 fs-4 w-100 px-0 text-start\" type=\"button\"\r\n");
      out.write("                        data-bs-toggle=\"collapse\" data-bs-target=\"#allCat\">\r\n");
      out.write("                        <h4 class=\"m-0\"><i class=\"fa fa-bars me-2\"></i>All Categories</h4>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse rounded-bottom\" id=\"allCat\">\r\n");
      out.write("                        <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                            <ul class=\"list-unstyled categories-bars\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Accessories</a>\r\n");
      out.write("                                        <span>(3)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Electronics & Computer</a>\r\n");
      out.write("                                        <span>(5)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Laptops & Desktops</a>\r\n");
      out.write("                                        <span>(2)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">Mobiles & Tablets</a>\r\n");
      out.write("                                        <span>(8)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"categories-bars-item\">\r\n");
      out.write("                                        <a href=\"#\">SmartPhone & Smart TV</a>\r\n");
      out.write("                                        <span>(5)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light bg-primary \">\r\n");
      out.write("                    <a href=\"#\" class=\"navbar-brand d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"display-5 text-secondary m-0\"><i\r\n");
      out.write("                                class=\"fas fa-shopping-bag text-white me-2\"></i>Electro</h1>\r\n");
      out.write("                        <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                        data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"fa fa-bars fa-1x\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                            <a href=\"seller-index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                            <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Products</a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <a href=\"seller-add-product.jsp\" class=\"dropdown-item\">Add Product</a>\r\n");
      out.write("                                    <a href=\"seller-view-product.jsp\" class=\"dropdown-item\">View Product</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"contact.jsp\" class=\"nav-item nav-link me-2\">Contact</a>\r\n");
      out.write("                            \r\n");
      out.write("                            ");

                                if(u==null)
                                {
                               
      out.write("\r\n");
      out.write("                               <a href=\"signup.jsp\" class=\"nav-item nav-link me-2\">Sign Up</a>\r\n");
      out.write("                               <a href=\"login.jsp\" class=\"nav-item nav-link me-2\">Login</a>\r\n");
      out.write("                               ");

                                }
                                else
                                {
                                
      out.write("	\r\n");
      out.write("                                	<a href=\"logout.jsp\" class=\"nav-item nav-link me-3\">Logout(");
      out.print( u.getFname()  );
      out.write(")</a>\r\n");
      out.write("                                 	 \r\n");
      out.write("                                 	 <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"logout.jsp\" class=\"nav-item nav-link me-5 \" data-bs-toggle=\"dropdown\"><img src=\"profile_picture/");
      out.print(u.getProfile_picture() );
      out.write("\" alt=\"Profile Picture\"  style=\"width:60px; height:60px; border-radius: 50%; \"></a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <a href=\"seller-profile.jsp\" class=\"dropdown-item\">Profile</a>\r\n");
      out.write("                                    <a href=\"seller-change-password.jsp\" class=\"dropdown-item\">Change Password</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                	\r\n");
      out.write("                                	\r\n");
      out.write("                                	\r\n");
      out.write("                              ");
  
                                }
                            
      out.write("\r\n");
      out.write("                            <div class=\"nav-item dropdown d-block d-lg-none mb-3\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">All Category</a>\r\n");
      out.write("                                <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                    <ul class=\"list-unstyled categories-bars\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Accessories</a>\r\n");
      out.write("                                                <span>(3)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Electronics & Computer</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Laptops & Desktops</a>\r\n");
      out.write("                                                <span>(2)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">Mobiles & Tablets</a>\r\n");
      out.write("                                                <span>(8)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"categories-bars-item\">\r\n");
      out.write("                                                <a href=\"#\">SmartPhone & Smart TV</a>\r\n");
      out.write("                                                <span>(5)</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar & Hero End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Contucts Start -->\r\n");
      out.write("    <div class=\"container-fluid contact py-5\">\r\n");
      out.write("        <div class=\"container py-2\">\r\n");
      out.write("            <div class=\"p-5 bg-light rounded\">\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 900px;\">\r\n");
      out.write("                            <h4 class=\"text-primary border-bottom border-primary border-2 d-inline-block pb-2\">Update Profile Form</h4>\r\n");
      out.write("                            <p class=\"mb-5 fs-5 text-dark\">We are here for you! how can we help, We are here for you!\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-11\">\r\n");
      out.write("                    \r\n");
      out.write("                    <b style=\"color:green;\">\r\n");
      out.write("                     ");

                        if(request.getAttribute("msg")!=null)
                        {
                        	out.println(request.getAttribute("msg"));
                        }
                     
      out.write("\r\n");
      out.write("                    </b>\r\n");
      out.write("                        <form name=\"frm\" action=\"UserController\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                        <input type=\"hidden\" class=\"form-control\" value=\"");
      out.print( u.getUsertype() );
      out.write("\" name=\"usertype\" id=\"usertype\" >\r\n");
      out.write("                            <div class=\"row g-4 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                                <div class=\"col-lg-12 col-xl-6\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" value=\"");
      out.print( u.getFname() );
      out.write("\" name=\"fname\" id=\"name\" >\r\n");
      out.write("                                        <label for=\"name\">First Name</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-12 col-xl-6\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" value=\"");
      out.print( u.getLname() );
      out.write("\" name=\"lname\" id=\"name\" >\r\n");
      out.write("                                        <label for=\"name\">Last Name</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-12 col-xl-6\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <input type=\"email\" class=\"form-control\" value=\"");
      out.print( u.getEmail() );
      out.write("\" name=\"email\" id=\"email\"  readonly=\"readonly\">\r\n");
      out.write("                                        <label for=\"email\"> Email</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-12 col-xl-6\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <input type=\"phone\" class=\"form-control\" value=\"");
      out.print( u.getMobile() );
      out.write("\" name=\"mobile\" id=\"phone\" >\r\n");
      out.write("                                        <label for=\"phone\">Your Mobile</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                       <img src=\"profile_picture/");
      out.print(u.getProfile_picture() );
      out.write("\" alt=\"Profile Picture\" style=\"width:100px; height:100px; border-radius: 50%;\" >\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                  <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <input type=\"file\" class=\"form-control\" name=\"profile_picture\" id=\"subject\" >\r\n");
      out.write("                                        <label for=\"subject\">Profile Picture</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div> \r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <div class=\"form-floating\">\r\n");
      out.write("                                        <textarea class=\"form-control\" name=\"address\"  id=\"message\"\r\n");
      out.write("                                            style=\"height: 120px\">");
      out.print(u.getAddress() );
      out.write("</textarea>\r\n");
      out.write("                                        <label for=\"address\">Address</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-3\">\r\n");
      out.write("                                    <button class=\"btn btn-primary w-100 py-3\" style=\"font-size: 25px; font-family: sans-serif; font-weight: 600\" name=\"action\" value=\"Update Profile\">Update Profile</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Contuct End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid footer py-5 wow fadeIn\" data-wow-delay=\"0.2s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-4 rounded mb-5\" style=\"background: rgba(255, 255, 255, .03);\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Address</h4>\r\n");
      out.write("                            <p class=\"mb-2\">123 Street New York.USA</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fas fa-envelope fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Mail Us</h4>\r\n");
      out.write("                            <p class=\"mb-2\">info@example.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fa fa-phone-alt fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Telephone</h4>\r\n");
      out.write("                            <p class=\"mb-2\">(+012) 3456 7890</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"rounded p-4\">\r\n");
      out.write("                        <div class=\"rounded-circle bg-secondary d-flex align-items-center justify-content-center mb-4\"\r\n");
      out.write("                            style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                            <i class=\"fab fa-firefox-browser fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"text-white\">Yoursite@ex.com</h4>\r\n");
      out.write("                            <p class=\"mb-2\">(+012) 3456 7890</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <div class=\"footer-item\">\r\n");
      out.write("                            <h4 class=\"text-primary mb-4\">Newsletter</h4>\r\n");
      out.write("                            <p class=\"text-white mb-3\">Dolor amet sit justo amet elitr clita ipsum elitr est.Lorem ipsum\r\n");
      out.write("                                dolor sit amet, consectetur adipiscing elit consectetur adipiscing elit.</p>\r\n");
      out.write("                            <div class=\"position-relative mx-auto rounded-pill\">\r\n");
      out.write("                                <input class=\"form-control rounded-pill w-100 py-3 ps-4 pe-5\" type=\"text\"\r\n");
      out.write("                                    placeholder=\"Enter your email\">\r\n");
      out.write("                                <button type=\"button\"\r\n");
      out.write("                                    class=\"btn btn-primary rounded-pill position-absolute top-0 end-0 py-2 mt-2 me-2\">SignUp</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Customer Service</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Contact Us</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Returns</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Order History</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Site Map</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Testimonials</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> My Account</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Unsubscribe Notification</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Information</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> About Us</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Delivery infomation</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Privacy Policy</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Terms & Conditions</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Warranty</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> FAQ</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Seller Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                    <div class=\"footer-item d-flex flex-column\">\r\n");
      out.write("                        <h4 class=\"text-primary mb-4\">Extras</h4>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Brands</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Gift Vouchers</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Affiliates</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Wishlist</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Order History</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Track Your Order</a>\r\n");
      out.write("                        <a href=\"#\" class=\"\"><i class=\"fas fa-angle-right me-2\"></i> Track Your Order</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row g-4 align-items-center\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-md-0\">\r\n");
      out.write("                    <span class=\"text-white\"><a href=\"#\" class=\"border-bottom text-white\"><i\r\n");
      out.write("                                class=\"fas fa-copyright text-light me-2\"></i>Your Site Name</a>, All right\r\n");
      out.write("                        reserved.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end text-white\">\r\n");
      out.write("\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->\r\n");
      out.write("                    <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->\r\n");
      out.write("                    <!--/*** you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". ***/-->\r\n");
      out.write("                    Designed By <a class=\"border-bottom text-white\" href=\"https://htmlcodex.com\">HTML Codex</a>.\r\n");
      out.write("                    Distributed By <a class=\"border-bottom text-white\" href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-primary btn-lg-square back-to-top\"><i class=\"fa fa-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
